# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build plugin

env:
  PLUGIN_NAME: obsidian-yfm-templater-plugin

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v1
    - name: zip directory
      run: zip -r ${{ env.PLUGIN_NAME }}.zip . -x ".git/*" ".github/*"
    - name: tar directory
      run: tar -czvf --exclude="./.git" --exclude="./.github" --exclude="${{ env.PLUGIN_NAME }}.zip" ${{ env.PLUGIN_NAME }}.tar.gz ./
#     - name: Github Tag Bump
#       uses: anothrNick/github-tag-action@1.33.0
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         WITH_V: true
